/*
Company: OptimaJet
Project: WorkflowEngine.NET Provider for Oracle
Version: 5.0
File: DropPersistenceObjects.sql
*/

DROP TABLE WORKFLOWINBOX;
DROP TABLE WORKFLOWAPPROVALHISTORY;
DROP TABLE WORKFLOWPROCESSINSTANCE;
DROP TABLE WORKFLOWPROCESSSCHEME;
DROP TABLE WORKFLOWPROCESSTIMER;
DROP TABLE WORKFLOWPROCESSTRANSITIONH;
DROP TABLE WORKFLOWPROCESSINSTANCEP;
DROP TABLE WORKFLOWSCHEME;
DROP TABLE WORKFLOWPROCESSINSTANCES;
DROP TABLE WORKFLOWGLOBALPARAMETER;

COMMIT;