BEGIN
EXECUTE IMMEDIATE 'CREATE TABLE WORKFLOWPROCESSSCHEME (
    ID RAW(16),
    SCHEME CLOB NOT NULL,
    DEFININGPARAMETERS CLOB NOT NULL,
    DEFININGPARAMETERSHASH NVARCHAR2(24) NOT NULL,
    SCHEMECODE NVARCHAR2(256) NOT NULL,
    ISOBSOLETE CHAR(1 BYTE) DEFAULT 0 NOT NULL,
    ROOTSCHEMECODE NVARCHAR2(256) NULL,
    ROOTSCHEMEID RAW(16) NULL,
    ALLOWEDACTIVITIES CLOB NULL,
    STARTINGTRANSITION CLOB NULL,
    CONSTRAINT PK_WORKFLOWPROCESSSCHEME PRIMARY KEY (ID) USING INDEX STORAGE ( INITIAL 64K NEXT 1M MAXEXTENTS UNLIMITED ))
LOGGING';
END;