BEGIN
EXECUTE IMMEDIATE 'CREATE TABLE WORKFLOWAPPROVALHISTORY (
    ID RAW(16),
    PROCESSID RAW(16) NOT NULL,
    IDENTITYID NVARCHAR2(256),
    ALLOWEDTO CLOB NULL,
    TRANSITIONTIME TIMESTAMP NULL,
    SORT NUMBER(19) NULL,
    INITIALSTATE NVARCHAR2(1024) NOT NULL,
    DESTINATIONSTATE NVARCHAR2(1024) NOT NULL,
    TRIGGERNAME NVARCHAR2(1024) NULL,
    COMMENTARY CLOB NULL,
    CONSTRAINT PK_WORKFLOWAPPROVALHISTORY PRIMARY KEY (ID) USING INDEX STORAGE ( INITIAL 64K NEXT 1M MAXEXTENTS UNLIMITED )
)
LOGGING';
END;