/*
Company: OptimaJet
Project: WorkflowEngine.NET Provider for Oracle
Version: 1.5
File: update_1_4_4_to_1_5.sql
*/

ALTER TABLE WORKFLOWPROCESSINSTANCE ADD
(
	PARENTPROCESSID RAW(16) NULL,
	ROOTPROCESSID RAW(16) NULL
);

UPDATE WORKFLOWPROCESSINSTANCE SET ROOTPROCESSID = ID WHERE ROOTPROCESSID IS NULL 

ALTER TABLE WORKFLOWPROCESSINSTANCE
  MODIFY ROOTPROCESSID  RAW(16) NOT NULL;

ALTER TABLE WORKFLOWPROCESSSCHEME ADD
(
	ROOTSCHEMECODE NVARCHAR2(256) NULL,
	ROOTSCHEMEID RAW(16) NULL,
	ALLOWEDACTIVITIES CLOB NULL,
	STARTINGTRANSITION CLOB NULL
);
