/*
Company: OptimaJet
Project: WorkflowEngine.NET Provider for Oracle
Version: 1.5.5
File: DropPersistenceObjects.sql
*/

DROP TABLE WORKFLOWINBOX;
DROP TABLE WORKFLOWPROCESSINSTANCE;
DROP TABLE WORKFLOWPROCESSSCHEME;
DROP TABLE WORKFLOWPROCESSTIMER;
DROP TABLE WORKFLOWPROCESSTRANSITIONH;
DROP TABLE WORKFLOWPROCESSINSTANCEP;
DROP TABLE WORKFLOWSCHEME;
DROP TABLE WORKFLOWPROCESSINSTANCES;
DROP TABLE WORKFLOWGLOBALPARAMETER;

COMMIT;