/*
Company: OptimaJet
Project: WorkflowEngine.NET Provider for Oracle
Version: 2.0
File: update_1_5_to_2_0.sql
*/

ALTER TABlE WORKFLOWPROCESSINSTANCES ADD STATUSNEW NUMERIC(3) NULL;
UPDATE WORKFLOWPROCESSINSTANCES SET STATUSNEW = TO_NUMBER(STATUS);
ALTER TABlE WORKFLOWPROCESSINSTANCES MODIFY STATUSNEW NUMERIC(3) NOT NULL;
ALTER TABlE WORKFLOWPROCESSINSTANCES DROP COLUMN STATUS;
ALTER TABLE WORKFLOWPROCESSINSTANCES RENAME COLUMN STATUSNEW TO STATUS;
COMMIT;