//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
using ExternalServicesAPI;

namespace ExternalServices
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "IccCftGetDocStatusBinding", Namespace = "http://IccCftBudget/IccDocStatus")]
    public partial class IccCftGetDocStatusService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback getDocStatusOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;
        /// <remarks/>
        public IccCftGetDocStatusService()
        {
            Url = Settings.GetDocStatusUrl;
            if (IsLocalFileSystemWebService(Url))
            {
                UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                useDefaultCredentialsSetExplicitly = true;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if (((IsLocalFileSystemWebService(base.Url)
                            && (useDefaultCredentialsSetExplicitly == false))
                            && (IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                useDefaultCredentialsSetExplicitly = true;
            }
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (string.IsNullOrEmpty(url))
            {
                return false;
            }
            var wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }

        /// <remarks/>
        public event getDocStatusCompletedEventHandler getDocStatusCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getDocStatusResponse", Namespace = "http://IccCftBudget/IccDocStatus")]
        public getDocStatusResponse getDocStatus([System.Xml.Serialization.XmlElementAttribute("getDocStatus", Namespace = "http://IccCftBudget/IccDocStatus")] getDocStatus getDocStatus1)
        {
            object[] results = this.Invoke("getDocStatus", new object[] {
                    getDocStatus1});
            return ((getDocStatusResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetDocStatus(getDocStatus getDocStatus1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getDocStatus", new object[] {
                    getDocStatus1}, callback, asyncState);
        }

        /// <remarks/>
        public getDocStatusResponse EndgetDocStatus(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((getDocStatusResponse)(results[0]));
        }

        /// <remarks/>
        public void getDocStatusAsync(getDocStatus getDocStatus1)
        {
            this.getDocStatusAsync(getDocStatus1, null);
        }

        /// <remarks/>
        public void getDocStatusAsync(getDocStatus getDocStatus1, object userState)
        {
            if ((this.getDocStatusOperationCompleted == null))
            {
                this.getDocStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDocStatusOperationCompleted);
            }
            this.InvokeAsync("getDocStatus", new object[] {
                    getDocStatus1}, this.getDocStatusOperationCompleted, userState);
        }

        private void OngetDocStatusOperationCompleted(object arg)
        {
            if ((this.getDocStatusCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDocStatusCompleted(this, new getDocStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://IccCftBudget/IccDocStatus")]
    public partial class getDocStatus
    {

        private DocStatusRequest getDocStatusRequestField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public DocStatusRequest getDocStatusRequest
        {
            get
            {
                return this.getDocStatusRequestField;
            }
            set
            {
                this.getDocStatusRequestField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://IccCftBudget/bo/docstatus")]
    public partial class DocStatusRequest
    {

        private string docNumField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string docNum
        {
            get
            {
                return this.docNumField;
            }
            set
            {
                this.docNumField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://IccCftBudget/bo/docstatus")]
    public partial class DocStatusResponse
    {

        private string statusField;

        private string descrField;

        private string payDocNumField;

        private System.DateTime payDocDateField;

        private bool payDocDateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descr
        {
            get
            {
                return this.descrField;
            }
            set
            {
                this.descrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string payDocNum
        {
            get
            {
                return this.payDocNumField;
            }
            set
            {
                this.payDocNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime payDocDate
        {
            get
            {
                return this.payDocDateField;
            }
            set
            {
                this.payDocDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool payDocDateSpecified
        {
            get
            {
                return this.payDocDateFieldSpecified;
            }
            set
            {
                this.payDocDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://IccCftBudget/IccDocStatus")]
    public partial class getDocStatusResponse
    {

        private DocStatusResponse getDocStatusResponse1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("getDocStatusResponse", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public DocStatusResponse getDocStatusResponse1
        {
            get
            {
                return this.getDocStatusResponse1Field;
            }
            set
            {
                this.getDocStatusResponse1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getDocStatusCompletedEventHandler(object sender, getDocStatusCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDocStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getDocStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public getDocStatusResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((getDocStatusResponse)(this.results[0]));
            }
        }
    }
}
